##===- lib/Transforms/Prospar/Makefile -----------------------*- Makefile -*-===##
#
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

LEVEL = ../../..
LIBRARYNAME = LLVMProspar
LOADABLE_MODULE = 1
BUILD_ARCHIVE = 1
USEDLIBS =

include $(LEVEL)/Makefile.common
